### ISSUE TITLE
Help with csv generation.

### ISSUE THREAD

**Issue by collegeimprovements** [stevenbarragan/julia_builder#5]
Hello steven,

thanks for this excellent gem.
I know this might not be supported but I'm opening this issue for asking your help.
On my production server, I need to implement the export functionality.
I fetched the users in `users` variable.
I also made the `UserCsv` class.
Unfortunately, when I tried to run `UserCsv.build(users)`, it didn't work.

Can you help us here ?

``` ruby
UserCsv.build(users)
TypeError: can't convert Hash into String
    from org/jruby/RubyFile.java:340:in `initialize'
    from org/jruby/RubyIO.java:1177:in `open'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/lib/ruby/1.8/csv.rb:326:in `open_writer'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/lib/ruby/1.8/csv.rb:111:in `generate'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/lib/ruby/gems/shared/gems/julia_builder-0.1.4/lib/julia/builder.rb:20:in `build'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/lib/ruby/gems/shared/gems/julia_builder-0.1.4/lib/julia/builder.rb:32:in `build'
    from (irb):27:in `evaluate'
    from org/jruby/RubyKernel.java:1096:in `eval'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/lib/ruby/1.8/irb.rb:158:in `eval_input'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/lib/ruby/1.8/irb.rb:271:in `signal_status'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/lib/ruby/1.8/irb.rb:155:in `eval_input'
    from org/jruby/RubyKernel.java:1501:in `loop'
    from org/jruby/RubyKernel.java:1250:in `catch'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/lib/ruby/1.8/irb.rb:154:in `eval_input'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/lib/ruby/1.8/irb.rb:71:in `start'
    from org/jruby/RubyKernel.java:1250:in `catch'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/lib/ruby/1.8/irb.rb:70:in `start'
    from /opt/tibco6.0.1v2-GA/tibbr/6.0/tools/jruby/bin/irb:13:in `(root)'
```

**Comment by stevenbarragan** [comment]
Hi,

Could you share your UserCSV class as well?

**Comment by collegeimprovements** [comment]
``` ruby
class UserCsv < Julia::Builder
  column 'First Name', :first_name
  column 'Last Name', :last_name  
end
```

Is there any specific location where I need put this class ? What you suggest? Sorry for my ignorance.

**Comment by stevenbarragan** [comment]
`CSV.generate` works different on ruby `1.8` and `1.9+`, could you try with a newer version?

**Comment by stevenbarragan** [comment]
You can create your generator on `lib` folder. You can create a namespace like

``` ruby
# lib/builder/user.rb

module Builder
   class User < Julia::Builder
      ...
   end
end
```

And generate the csv like 

``` ruby
Builder::User.generate(users)
```

_updated: Added missing `class` keyword_

**Comment by beechnut** [comment]
I think in the above code block, you'd need the `class` keyword:

``` ruby
module Builder
  class User < Julia::Builder
    # ...
  end
end
```

If you need CSV generators on specific resources, you could also treat them as serializers. You can just create a folder `app/serializers`, and those files will be automatically included.

``` ruby
# app/serializers/user_csv_serializer.rb

class UserCsvSerializer < Julia::Builder
  # ...
end

# elsewhere
UserCsvSerializer.generate(User.all)
```

**Comment by stevenbarragan** [comment]
~~:+1:missing keyword class~~ Fixed.

Great idea using the serializers folder

**Comment by collegeimprovements** [comment]
excellent :) thank you @stevenbarragan  @beechnut  for your comment. I'll try it today :)

**Comment by stevenbarragan** [comment]
you're welcome, let me know if anything comes up.
